
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "12bb59d3ea7f2831c34b32fef5877f24bcd49923",
 "version": "4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
